name: core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  alice: ^0.1.4
  retrofit: any
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  hydrated_bloc: ^6.0.1
  google_sign_in: ^4.5.3
  firebase_auth: ^0.18.0+1
  json_serializable: ^3.3.0
  uni_links: ^0.4.0
  firebase_messaging: ^7.0.0
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  #  facebook_app_events: ^0.7.0
  #  sign_in_with_apple: ^2.5.2
#  firebase_crashlytics: ^0.1.4+1

  # This is our modular
  shared:
    path: ../shared
  BaseApp:
    path: ../../flutter_base_project

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_resolvers: ^1.3.10
  build_runner: any

dependency_overrides:
  analyzer: '0.39.14'

flutter: